### ISSUE TITLE
Learning in an unnatural way

### ISSUE THREAD

**Issue by arashsajjadi** [reiniscimurs/TD3_Separate_Action#1]
Hello, good time. I retrained your model several times and even changed the hyperparameters. But continuously, while increasing the reward, it does not learn to run like a cheetah. And it permanently reverses and tries to use its back to move. Also, I set `max_timesteps` not only large enough, but in some runs, I put it almost three times the maximum value you reported. Do you have any comments?

**Comment by reiniscimurs** [comment]
The learning is quite random and most likely you have encountered a local minimum in your training. Try experimenting with different seed numbers and running the training a couple of more times until the network learns proper behavior.

**Comment by arashsajjadi** [comment]
Thank you. Is there an exact number of the world record to know if this number we have reached is good or not?

**Comment by reiniscimurs** [comment]
Quick google search only returns [this](https://paperswithcode.com/paper/generalized-state-dependent-exploration-for). Sorry, I have no idea if some leaderboards exist for this.

**Comment by arashsajjadi** [comment]
Thank you very much, I had seen this, but I had reached 4000 points in the first runs, I felt that maybe an update changed the scoring system.
